app = "saasbase-soketi"

primary_region = "fra"

[build]
image = "quay.io/soketi/soketi:1.5-16-alpine"

[[services]]
  internal_port = 6001
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
