app = "saasbase-soketi"

primary_region = "fra"

[build]
image = "quay.io/soketi/soketi:e446df8e3e06b8430d75cf58555bc409bf240a4e-16-distroless"

[env]
SOCKET_HOST = "0.0.0.0"
SOCKET_PORT = "6001"

[[services]]
  internal_port = 6001
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
